# Generated by Django 2.2.6 on 2020-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_squashed_0006_auto_20200929_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletoprofession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
