# Generated by Django 2.2.6 on 2020-10-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200929_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='noimg.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
