# Generated by Django 2.2.6 on 2020-04-18 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200416_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletoprofession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
