# Generated by Django 2.2.6 on 2020-06-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200621_1936'),
        ('account', '0004_profiletoprofession_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_mbs', to='chat.Room')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_from_profile', to='account.Profile')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_to_profile', to='account.Profile')),
            ],
        ),
    ]
