# Generated by Django 2.2.6 on 2020-11-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0005_auto_20201121_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Просмотры')),
                ('product_or_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_product_or_service', to='shops.ServiceType', verbose_name='Продукт или услуга')),
            ],
        ),
    ]
