# Generated by Django 2.2.6 on 2020-11-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='amount_of_comments',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Комментарии'),
        ),
    ]
