# Generated by Django 2.2.6 on 2020-12-26 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics_shop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_shop', to='shops.Shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='product_or_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_product_or_service', to='shops.ServiceType', verbose_name='Продукт или услуга'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='st_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats_shop', to='management.Statistics_shop', verbose_name='Статистика магазина'),
        ),
    ]
