# Generated by Django 2.2.6 on 2020-11-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_statistics_amount_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='orders',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Заказы'),
        ),
    ]
