# Generated by Django 2.2.6 on 2020-11-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_statistics_orders_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='paid_orders',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Олплаченные заказы'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='paid_orders_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Стоимость оплаченных заказов'),
        ),
    ]
