# Generated by Django 2.2.6 on 2020-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20201125_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='in_cart',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='В корзине'),
        ),
    ]
