# Generated by Django 2.2.6 on 2020-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_statistics_in_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='paid_orders',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Оплаченные заказы'),
        ),
    ]
