# Generated by Django 2.2.6 on 2020-12-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20201202_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Рейтинг'),
        ),
    ]
