# Generated by Django 2.2.6 on 2020-12-02 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20201202_2132'),
        ('management', '0008_statistics_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Просмотры товаров')),
                ('amount_of_comments', models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Комментарии')),
                ('orders', models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Заказы')),
                ('orders_cost', models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Стоимость заказов')),
                ('paid_orders', models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Оплаченные заказы')),
                ('paid_orders_cost', models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Стоимость оплаченных заказов')),
                ('in_cart', models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='В корзине')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Средний рейтинг товаров')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_shop', to='shops.Shop', verbose_name='Магазин')),
            ],
        ),
    ]
