# Generated by Django 2.2.6 on 2020-12-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_statistics_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics_shop',
            name='amount_of_comments',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Комментарии товаров'),
        ),
        migrations.AlterField(
            model_name='statistics_shop',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat_shop', to='shops.Shop', verbose_name='Магазин'),
        ),
    ]
