# Generated by Django 2.2.6 on 2020-12-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20201203_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics_shop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_shop', to='shops.Shop', verbose_name='Магазин'),
        ),
    ]
