# Generated by Django 2.2.6 on 2020-12-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20201203_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='st_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats_shop', to='management.Statistics_shop', verbose_name='Статистика магазина'),
        ),
    ]
