# Generated by Django 2.2.6 on 2020-12-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_statistics_st_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='statistics_shop',
            name='quantity_of_products_and_services',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Количество товаров и услуг'),
        ),
    ]
