# Generated by Django 2.2.6 on 2021-01-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20201204_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='views_per_day',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Просмотры за день'),
        ),
    ]
