# Generated by Django 2.2.6 on 2021-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20210103_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='views_per_day',
            field=models.CharField(default='', max_length=100000, verbose_name='Просмотры за день'),
        ),
    ]
