# Generated by Django 2.2.6 on 2020-09-29 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_content_typeofwork'), ('projects', '0003_auto_20200509_2136'), ('projects', '0004_benchmark_content_module_project_typeofwork'), ('projects', '0005_auto_20200509_2242'), ('projects', '0006_auto_20200510_1901'), ('projects', '0007_benchmark_content_file_image_module_project_text_typeofwork_video'), ('projects', '0008_auto_20200511_2138'), ('projects', '0009_benchmark_content_file_image_module_project_text_typeofwork_video'), ('projects', '0010_auto_20200523_2347'), ('projects', '0011_auto_20200524_2150'), ('projects', '0012_remove_module_producer'), ('projects', '0013_module_producer'), ('projects', '0014_auto_20200524_2331'), ('projects', '0015_auto_20200530_1738'), ('projects', '0016_auto_20200530_1743'), ('projects', '0017_auto_20200530_1746'), ('projects', '0018_auto_20200530_1748'), ('projects', '0019_auto_20200530_1755'), ('projects', '0020_auto_20200530_1759'), ('projects', '0021_auto_20200530_1803'), ('projects', '0022_auto_20200530_1854'), ('projects', '0023_auto_20200530_1856'), ('projects', '0024_auto_20200530_1857'), ('projects', '0025_auto_20200531_0126'), ('projects', '0026_auto_20200620_1718'), ('projects', '0027_projectrespond'), ('projects', '0028_projectrespond_created'), ('projects', '0029_auto_20200624_1550'), ('projects', '0030_delete_projectrespond'), ('projects', '0031_projectrespond')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_profiletoprofession_created'),
        ('shops', '0006_service_servicegalary_serviceimage'),
        ('shops', '0026_auto_20200522_2333'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_for_project', to='shops.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.TypeOfWork')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_for_project', to='shops.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('complited', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.TypeOfWork')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('complited', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/images/%Y/%m/%d/')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_for_project', to='shops.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='projects/files/%Y/%m/%d/')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_for_project', to='shops.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='projects.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False, verbose_name='статус')),
                ('deadline', models.DateField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='projects.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='shops.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='producer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Producer'),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childrens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_childrens', to='projects.Module')),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_parents', to='projects.Module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='parents',
            field=models.ManyToManyField(related_name='childs', through='projects.Family', to='projects.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='account.Profession'),
        ),
        migrations.CreateModel(
            name='ProjectRespond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('garanty', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to='projects.Module')),
                ('responded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
