# Generated by Django 2.2.6 on 2020-09-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_squashed_0031_projectrespond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.DeleteModel(
            name='TypeOfWork',
        ),
    ]
