# Generated by Django 2.2.6 on 2020-12-26 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_for_project', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='typeofwork',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.TypeOfWork'),
        ),
        migrations.AddField(
            model_name='text',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_for_project', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='projectrespond',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to='projects.Module'),
        ),
        migrations.AddField(
            model_name='projectrespond',
            name='responded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.TypeOfWork'),
        ),
        migrations.AddField(
            model_name='producer',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='module',
            name='parents',
            field=models.ManyToManyField(related_name='childs', through='projects.Family', to='projects.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='producer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Producer'),
        ),
        migrations.AddField(
            model_name='module',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='account.Profession'),
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='image',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_for_project', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='file',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_for_project', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='family',
            name='childrens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_childrens', to='projects.Module'),
        ),
        migrations.AddField(
            model_name='family',
            name='parents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_parents', to='projects.Module'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='projects.Module'),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='projects.Module'),
        ),
    ]
