# Generated by Django 2.2.6 on 2020-05-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200509_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='module',
        ),
        migrations.RemoveField(
            model_name='file',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='image',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='module',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='module',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.RemoveField(
            model_name='text',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='typeofwork',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='video',
            name='producer',
        ),
        migrations.DeleteModel(
            name='Benchmark',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='TypeOfWork',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
