# Generated by Django 2.2.6 on 2020-05-23 18:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_benchmark_content_file_image_module_project_text_typeofwork_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='level',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='module',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='module',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tree_id',
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('childrens', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='projects.Module')),
                ('parents', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='projects.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
