# Generated by Django 2.2.6 on 2020-05-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200523_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='shops.Shop'),
        ),
    ]
