# Generated by Django 2.2.6 on 2020-05-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200524_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='producer',
        ),
    ]
