# Generated by Django 2.2.6 on 2020-05-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0026_auto_20200522_2333'),
        ('projects', '0012_remove_module_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='shops.Shop'),
        ),
    ]
