# Generated by Django 2.2.6 on 2020-05-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0026_auto_20200522_2333'),
        ('projects', '0013_module_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='producer',
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='shops.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='service_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Producer'),
        ),
    ]
