# Generated by Django 2.2.6 on 2020-05-30 12:38

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200524_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='childrens',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_childrens', to='projects.Module'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parents',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_parents', to='projects.Module'),
        ),
    ]
