# Generated by Django 2.2.6 on 2020-05-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200530_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='childrens',
            new_name='children',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='parents',
            new_name='parent',
        ),
    ]
