# Generated by Django 2.2.6 on 2020-05-30 12:48

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200530_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='children',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.Module'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parent',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='projects.Module'),
        ),
    ]
