# Generated by Django 2.2.6 on 2020-05-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200530_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='childrens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='projects.Module'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='projects.Module'),
        ),
    ]
