# Generated by Django 2.2.6 on 2020-05-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200530_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='parents',
            field=models.ManyToManyField(related_name='childs', through='projects.Family', to='projects.Module'),
        ),
        migrations.AlterField(
            model_name='family',
            name='childrens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_childrens', to='projects.Module'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_parents', to='projects.Module'),
        ),
    ]
