# Generated by Django 2.2.6 on 2020-05-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200530_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='parents',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
