# Generated by Django 2.2.6 on 2020-05-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20200530_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childrens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_childrens', to='projects.Module')),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fam_parents', to='projects.Module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='parents',
            field=models.ManyToManyField(related_name='childs', through='projects.Family', to='projects.Module'),
        ),
    ]
