# Generated by Django 2.2.6 on 2020-05-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20200530_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='service_type',
            new_name='producer',
        ),
    ]
