# Generated by Django 2.2.6 on 2020-06-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profiletoprofession_created'),
        ('projects', '0025_auto_20200531_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='account.Profession'),
        ),
        migrations.AlterField(
            model_name='module',
            name='producer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Producer'),
        ),
    ]
