# Generated by Django 2.2.6 on 2020-06-24 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_projectrespond'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrespond',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 24, 10, 39, 59, 773531, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
