# Generated by Django 2.2.6 on 2020-06-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_projectrespond_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrespond',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to='projects.Module'),
        ),
    ]
