# Generated by Django 2.2.6 on 2020-06-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20200624_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRespond',
        ),
    ]
