# Generated by Django 2.2.6 on 2020-06-24 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0030_delete_projectrespond'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRespond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('garanty', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to='projects.Module')),
                ('responded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
