# Generated by Django 2.2.6 on 2020-08-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0026_auto_20200522_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('service_or_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_product', to='shops.ServiceType', verbose_name='Продукт или услуга')),
            ],
        ),
    ]
