# Generated by Django 2.2.6 on 2020-08-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200828_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product_or_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_product_or_service', to='shops.ServiceType', verbose_name='Продукт или услуга'),
        ),
    ]
