# Generated by Django 2.2.6 on 2020-08-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
