# Generated by Django 2.2.6 on 2020-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='add_text',
            field=models.TextField(default='', verbose_name='Текст дополнения'),
        ),
    ]
