# Generated by Django 2.2.6 on 2020-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_comment_add_text_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_text_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], decimal_places=0, default='5', max_digits=1, verbose_name='Оценка'),
        ),
    ]
