# Generated by Django 2.2.6 on 2020-09-19 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0011_auto_20200917_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст комментария'),
        ),
        migrations.CreateModel(
            name='AddComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255, verbose_name='Текст дополнения к комментарию')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор дополнения к комментарию')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_comments', to='comments.Comment', verbose_name='Комментарий')),
            ],
        ),
    ]
