# Generated by Django 2.2.6 on 2020-09-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20200919_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/comments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='addcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_comments', to='comments.Comment', verbose_name='Комментарий'),
        ),
    ]
