# Generated by Django 2.2.6 on 2020-09-24 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_auto_20200922_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product_or_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_product_or_service', to='shops.ServiceType', verbose_name='Продукт или услуга'),
        ),
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_comment', models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/%d/', verbose_name='Изображение')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_in_comment', to='comments.Comment', verbose_name='Комментарий')),
            ],
        ),
    ]
