# Generated by Django 2.2.6 on 2020-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0016_auto_20200924_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecomment',
            name='image_comment',
        ),
        migrations.AddField(
            model_name='imagecomment',
            name='images_comment',
            field=models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/%d/', verbose_name='Изображения'),
        ),
    ]
