# Generated by Django 2.2.6 on 2020-10-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0019_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='comment',
        ),
        migrations.AddField(
            model_name='complaint',
            name='comment_or_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='comments.CommentType', verbose_name='Комментарий'),
        ),
    ]
