# Generated by Django 2.2.6 on 2020-10-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0020_auto_20201005_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50, verbose_name='Жалоба')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор жалобы')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='comments.Comment', verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50, verbose_name='Жалоба')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_reply_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор жалобы')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='comments.Reply', verbose_name='Ответ')),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
