# Generated by Django 2.2.6 on 2020-06-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='message_html',
        ),
    ]
