# Generated by Django 2.2.6 on 2020-04-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200422_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary',
            name='title',
            field=models.CharField(default='basic', max_length=200, unique=True),
        ),
    ]
