# Generated by Django 2.2.6 on 2020-04-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200422_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galary',
            options={'ordering': ['created'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.AlterField(
            model_name='galary',
            name='title',
            field=models.CharField(default='basic', max_length=200),
        ),
    ]
