# Generated by Django 2.2.6 on 2020-04-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20200422_2253'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_galary', to='shops.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='template_prefix',
            field=models.SlugField(help_text='obana.ru/THIS/...', max_length=92, unique=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.Image')),
                ('is_main', models.BooleanField(default=False)),
                ('galary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.ProductGalary')),
            ],
            bases=('images.image',),
        ),
    ]
