# Generated by Django 2.2.6 on 2020-04-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20200424_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgalary',
            options={'verbose_name': 'Галерея товаров', 'verbose_name_plural': 'Галереи товаров'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AddField(
            model_name='productgalary',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
