# Generated by Django 2.2.6 on 2020-05-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20200424_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgalary',
            name='main_image_pic',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
