# Generated by Django 2.2.6 on 2020-10-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20201001_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='productgalary',
            name='main_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
