# Generated by Django 2.2.6 on 2020-05-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_productgalary_main_image_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgalary',
            name='main_image_pic',
        ),
    ]
