# Generated by Django 2.2.6 on 2020-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20201002_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='service',
            name='views',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999, verbose_name='Просмотры'),
        ),
    ]
