# Generated by Django 2.2.6 on 2020-11-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20201121_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.RemoveField(
            model_name='service',
            name='views',
        ),
    ]
