# Generated by Django 2.2.6 on 2020-05-13 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_service_servicegalary_serviceimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_information',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_information',
            new_name='information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_counter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.RemoveField(
            model_name='service',
            name='buy_counter',
        ),
        migrations.RemoveField(
            model_name='service',
            name='views',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shops.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shops.Shop'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='shops.Category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='shops.Shop'),
        ),
    ]
