# Generated by Django 2.2.6 on 2020-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20201121_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Рейтинг'),
        ),
    ]
