# Generated by Django 2.2.6 on 2020-12-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20201202_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
    ]
