# Generated by Django 2.2.6 on 2020-05-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20200513_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картинка товара', 'verbose_name_plural': 'Картинки товаров'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Картинка услуги', 'verbose_name_plural': 'Картинки услуг'},
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='owner',
        ),
    ]
