# Generated by Django 2.2.6 on 2020-05-16 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0008_auto_20200514_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='contact_email',
            field=models.EmailField(default='contact@yourstore.com', help_text='Контактный емайл для ЭТОГО магазина', max_length=254, verbose_name='Контактный e-mail'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='contact_phone',
            field=models.CharField(default='', help_text='Контактный телефон для ЭТОГО магазина', max_length=128, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(help_text='Название для владельца и персонала', max_length=92, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(help_text='Название для клиентов', max_length=92, verbose_name='Вывеска'),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_for_shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='shops.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product/images/%Y/%m/%d/')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_for_shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='product/files/%Y/%m/%d/')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_for_shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
