# Generated by Django 2.2.6 on 2020-05-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20200516_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='text',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
