# Generated by Django 2.2.6 on 2020-05-17 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0011_file_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='employes',
            field=models.ManyToManyField(related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
