# Generated by Django 2.2.6 on 2020-05-18 13:27

from django.db import migrations
import shops.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_shop_employes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcontent',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='productcontent',
            name='order',
            field=shops.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
