# Generated by Django 2.2.6 on 2020-05-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_auto_20200518_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.RemoveField(
            model_name='image',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='productcontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='productcontent',
            name='product',
        ),
        migrations.RemoveField(
            model_name='text',
            name='product',
        ),
        migrations.RemoveField(
            model_name='text',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProductContent',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
