# Generated by Django 2.2.6 on 2020-05-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_file_image_productcontent_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='productgalary',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='service_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.ServiceType'),
        ),
        migrations.AddField(
            model_name='productgalary',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galary', to='shops.ServiceType'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.ServiceType'),
        ),
    ]
