# Generated by Django 2.2.6 on 2020-05-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_auto_20200519_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='service_type',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shops.ServiceType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shops.ServiceType'),
            preserve_default=False,
        ),
    ]
