# Generated by Django 2.2.6 on 2020-05-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_auto_20200519_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='galary',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_ptr',
        ),
        migrations.DeleteModel(
            name='ProductGalary',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
