# Generated by Django 2.2.6 on 2020-05-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20200422_2253'),
        ('shops', '0020_auto_20200519_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.URLField(blank=True, null=True)),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galary', to='shops.ServiceType')),
            ],
            options={
                'verbose_name': 'Галерея товаров',
                'verbose_name_plural': 'Галереи товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.Image')),
                ('is_main', models.BooleanField(default=False)),
                ('galary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.ProductGalary')),
            ],
            options={
                'verbose_name': 'Картинка товара',
                'verbose_name_plural': 'Картинки товаров',
            },
            bases=('images.image',),
        ),
    ]
