# Generated by Django 2.2.6 on 2020-05-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0021_productgalary_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='galary',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='image_ptr',
        ),
        migrations.DeleteModel(
            name='ServiceGalary',
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
