# Generated by Django 2.2.6 on 2020-05-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0022_auto_20200519_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgalary',
            name='service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='galary', to='shops.ServiceType'),
            preserve_default=False,
        ),
    ]
