# Generated by Django 2.2.6 on 2020-05-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0025_file_image_productcontent_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcontent',
            options={'ordering': ['order']},
        ),
    ]
