# Generated by Django 2.2.6 on 2020-08-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0027_auto_20200818_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='title',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='название'),
            preserve_default=False,
        ),
    ]
