# Generated by Django 2.2.6 on 2020-08-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0029_slide_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
