# Generated by Django 2.2.6 on 2020-08-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0031_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
