# Generated by Django 2.2.6 on 2020-08-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0033_slide_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='service_type',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.ServiceType'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.ServiceType'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
