# Generated by Django 2.2.6 on 2020-04-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20200424_1536'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
