# Generated by Django 2.2.6 on 2020-04-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200425_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paiment_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
