# Generated by Django 2.2.6 on 2020-04-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paiment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paiment_id',
            new_name='payment_id',
        ),
    ]
